// Login action types
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const INCRCOUNTER = 'INCRCOUNTER'
export const DECRCOUNTER = 'DECRCOUNTER'
export const ADDTOCART = 'ADDTOCART'
export const ITEMSINCART = 'ITEMSINCART'
export const ADDITEMTOCART = 'ADDITEMTOCART'
